spring.application.name=discovery-server

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8761

# logging
logging.level.org.springframework=DEBUG
logging.pattern.console=%d{HH:mm:ss} %level: %msg%n
#for structured logging
logging.structured.format.file=ecs
logging.file.name=log.json